spring.application.name=LucasHJDS_Mercado-pago
spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=50MB

spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3306/mpusers}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:user}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:senha}
spring.jpa.hibernate.ddl-auto=update

mercadopago.public-key=${MERCADOPAGO_PUBLIC_KEY:APP}
mercadopago.access.token=${MERCADOPAGO_ACCESS_TOKEN:APP}
mercadopago.webhook.secret=${MERCADOPAGO_WEBHOOK_SECRET:APP}

app.base-url=${BASE_URL_SPRING:http://localhost:8080}